import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Heart, Eye } from 'lucide-react';
import { formatPrice, placeholder, timeAgo, campusColor } from '../lib/utils';
export default function ProductCard({ p }) {
    const cover = p.cover || placeholder(p.id, 400, 300, p.category_icon || '🛍');
    const discount = p.original_price ? Math.round((p.price / p.original_price) * 10) : null;
    return (_jsxs(Link, { to: `/product/${p.id}`, className: "card overflow-hidden flex flex-col transition active:scale-[0.985]", children: [_jsxs("div", { className: "relative aspect-[4/3] bg-zinc-50 overflow-hidden", children: [_jsx("img", { src: cover, alt: p.title, className: "w-full h-full object-cover", loading: "lazy" }), discount && (_jsxs("span", { className: "absolute top-2 left-2 px-1.5 py-0.5 rounded-md bg-red-500/90 text-white text-[10px] font-bold", children: [discount, "\u6298"] })), p.course_name && (_jsxs("span", { className: "absolute bottom-2 left-2 chip chip-brand", children: ["\uD83D\uDCDA ", p.course_name.length > 8 ? p.course_name.slice(0, 8) + '…' : p.course_name] })), p.campus && (_jsx("span", { className: `absolute top-2 right-2 chip !bg-white/90 ${campusColor(p.campus)} !py-0.5`, children: p.campus }))] }), _jsxs("div", { className: "p-2.5 flex flex-col gap-1.5 flex-1", children: [_jsx("h3", { className: "text-sm text-zinc-800 line-clamp-2 leading-snug min-h-[2.5rem]", children: p.title }), _jsxs("div", { className: "flex items-baseline gap-1.5 mt-0.5", children: [_jsx("span", { className: "text-base font-bold text-red-500 leading-none", children: formatPrice(p.price) }), p.original_price ? (_jsx("span", { className: "text-[11px] text-zinc-400 line-through", children: formatPrice(p.original_price) })) : null] }), _jsxs("div", { className: "flex items-center justify-between text-[11px] text-zinc-500 mt-1 pt-1.5 border-t border-zinc-50", children: [_jsxs("div", { className: "flex items-center gap-1 min-w-0", children: [_jsx("span", { className: `px-1.5 py-0.5 rounded text-[10px] bg-zinc-100 text-zinc-600 whitespace-nowrap`, children: p.condition }), _jsx("span", { className: "truncate", children: timeAgo(p.created_at) })] }), _jsxs("div", { className: "flex items-center gap-2 shrink-0", children: [_jsxs("span", { className: "flex items-center gap-0.5", children: [_jsx(Eye, { size: 12 }), p.view_count || 0] }), _jsxs("span", { className: "flex items-center gap-0.5", children: [_jsx(Heart, { size: 12 }), p.fav_count || 0] })] })] })] })] }));
}
